=== Andjelaaa/XML-i-veb-servisi/dokumenti/projekat/src/main/resources/seme/zalba_odluke.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0">
    <xs:element name="zalba_odluke">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="podnosilac_zalbe"/>
                <xs:element name="poverenik" type="TPoverenik"/>
                <xs:element name="naslov">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                            <xs:maxLength value="150"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="tekst_zalbe">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element ref="podnosilac_zalbe"/>
                            <xs:element name="organ_vlasti">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="naziv_organa" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" name="p">
                                <xs:complexType mixed="true">
                                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                                        <xs:element name="datum"/>
                                        <xs:element name="razlog" type="xs:string"/>
                                        <xs:element name="broj_zalbe"/>
                                        <xs:element name="godina_odbijanja"/>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                            <xs:element minOccurs="0" name="podaci_o_trenutku">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="mesto" type="xs:string"/>
                                        <xs:element name="datum"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="napomena">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="tacke">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                        <xs:element name="tacka">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="broj"
                                                  type="xs:positiveInteger"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="podnosilac_zalbe">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naziv_podnosioca" type="TPodnosilac"/>
                <xs:element name="adresa" type="TAdresa"/>
                <xs:element name="drugi_podaci_za_kontakt" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TPodnosilac">
        <xs:sequence>
            <xs:element name="ime" type="xs:string"/>
            <xs:element name="prezime" type="xs:string"/>
            <xs:element name="naziv_firme" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAdresa" mixed="true">
        <xs:sequence>
            <xs:element name="ulica" type="xs:string" minOccurs="1"/>
            <xs:element name="broj" minOccurs="0" nillable="false" type="xs:string"/>
            <xs:element name="grad" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPoverenik">
        <xs:sequence>
            <xs:element name="naziv_poverenika">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="sediste_poverenika" type="TAdresa"> </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Andjelaaa/XML-i-veb-servisi/dokumenti/zalba_odluke.xml
<?xml version="1.0" encoding="UTF-8"?>
<zalba_odluke xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zalba_odluke.xsd">
    <podnosilac_zalbe>
        <naziv_podnosioca>
            <ime></ime>
            <prezime></prezime>
            <naziv_firme></naziv_firme>
        </naziv_podnosioca>
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <grad></grad>
        </adresa>
        <drugi_podaci_za_kontakt></drugi_podaci_za_kontakt>
        
    </podnosilac_zalbe>
    <poverenik>
        <naziv_poverenika>
                Повереникy за информације од јавног значаја и заштиту података о личности
        </naziv_poverenika>
        <sediste_poverenika>
            Aдреса за пошту:  
            <ulica>Булевар краља Александра</ulica>
            бр.
            <broj>15</broj> 
            <grad>
                Београд 
            </grad>
        </sediste_poverenika>
    </poverenik>
    <naslov>
           ЖАЛБА ПРОТИВ ОДЛУКЕ ОРГАНА ВЛАСТИ КОЈОМ ЈЕ ОДБИЈЕН ИЛИ ОДБАЧЕН ЗАТЕВ ЗА ПРИСТУП ИНФОРМАЦИЈИ
    </naslov>
    <tekst_zalbe>
            Жалбa
            <podnosilac_zalbe>
                <naziv_podnosioca>
                    <ime></ime>
                    <prezime></prezime>
                    <naziv_firme></naziv_firme>
                </naziv_podnosioca>
                <adresa>
                    <ulica></ulica>
                    <broj></broj>
                    <grad></grad>
                </adresa>
                <drugi_podaci_za_kontakt></drugi_podaci_za_kontakt>
                
            </podnosilac_zalbe>
            против решења-закључка
            <organ_vlasti>
                <naziv_organa></naziv_organa>
            </organ_vlasti>
            <p>
                Број
                <broj_zalbe></broj_zalbe>
                од
                <godina_odbijanja></godina_odbijanja>
                године.
            </p>
            <p>
                Наведеном одлуком органа власти(решењем, закључком, обавештењем у писаној
                форми са елементима одлуке) , супротно закону, одбијен-одбачен је мој захтев који
                сам поднео/ла- упутио/ла дана
                <datum></datum>
                године и тако ми ускраћено-онемогућено остваривање уставног и законског права на 
                слободан приступ информацијама од јавног значаја. Одлуку побијам у целости, односно 
                у делу којим
                <razlog></razlog>
                јер није заснована на Закону о слободном приступу информацијама од јавног значаја.
            </p>
            <p>
                На основу изнетих разлога, предлажем да Повереник уважи моју жалбу, поништи одлука првостепеног органа и омогући
                ми приступ траженој/им информацији/ма.
            </p>
            <p>
                Жалбу подносим благовремено, у законском року утврђеном у члану 22.ст. 1. Закона о слободном
                приступу информацијама од јавног значаја. 
            </p>
            <podaci_o_trenutku>
                У
                <mesto></mesto>
                ,дана
                <datum></datum> године
            </podaci_o_trenutku>
        
    </tekst_zalbe>
    <napomena>
        Напомена:
        <tacke>
            <tacka broj="1">
                У жалби се мора навести одлука која се побија( решење, закњучак, обавештење)
                назив органа који је одлуку донео, као и број и датум одлуке. Довољно је да жалилац
                наведе у жалби у ком погледу је незадовољан одлуком, с тим да жалбу не мора посебно
                приложити. 
            </tacka>
            <tacka broj ="2">
                Уз жалбу обавезно приложити копију поднетог захтева и доказ
                о његовој предаји-упућивању органу као и копију одлуке органа која се оспорава жалбом.
            </tacka>
        </tacke>
    </napomena>
</zalba_odluke>
